name: valinfo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  http: ^0.13.6
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  val_api: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  image_path: "lib/icon/wingman_icon.png"
  android: true
  ios: true
  

flutter:
  uses-material-design: true
  fonts:
    - family: Valorant
      fonts:
        - asset: fonts/Valorant Font.ttf

    - family: Din Next
      fonts:
        - asset: fonts/DINNextW1G-Black.otf
        - asset: fonts/DINNextW1G-BlackItalic.otf
        - asset: fonts/DINNextW1G-Bold.otf
        - asset: fonts/DINNextW1G-BoldItalic.otf
        - asset: fonts/DINNextW1G-Heavy.otf
        - asset: fonts/DINNextW1G-HeavyItalic.otf
        - asset: fonts/DINNextW1G-Italic.otf
        - asset: fonts/DINNextW1G-Light.otf
        - asset: fonts/DINNextW1G-Medium.otf
        - asset: fonts/DINNextW1G-MediumItalic.otf
        - asset: fonts/DINNextW1G-Regular.otf
        - asset: fonts/DINNextW1G-UltraLight.otf
        - asset: fonts/DINNextW1G-UltraLightIt.otf

    - family: Mark Pro
      fonts:
        - asset: fonts/MARKPRO.OTF
        - asset: fonts/MARKPROBOLD.OTF
        - asset: fonts/MARKPROBOOK.OTF
        - asset: fonts/MARKPROEXTRALIGHT.OTF
        - asset: fonts/MARKPROHEAVY.OTF
        - asset: fonts/MARKPROLIGHT.OTF
        - asset: fonts/MARKPROMEDIUM.OTF

    - family: Bebas Neue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf